# Generated by Django 4.1.6 on 2023-02-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='symbol',
        ),
    ]
